version: "3.8"

services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    container_name: "db-stock_m"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "local"
    volumes:
      - "./src/main/resources/sql/:/docker-entrypoint-initdb.d"
