spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/stock_management
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect